chore:update

diff --git a/.github/workflows/github-pages.yml b/.github/workflows/github-pages.yml
--- a/.github/workflows/github-pages.yml
+++ b/.github/workflows/github-pages.yml
@@ -3,16 +3,16 @@ name: Deploy to GitHub Pages
 on:
   workflow_dispatch: {}
   push:
-    # branches:
-    #   - main
-    # paths-ignore:
-    #   - 'README.md'
-    #   - 'LICENSE'
-    #   - '.github/**'
-    #   - '.gitignore'
-    #   - '.git/**'
-    #   - '.idea/**'
-    #   - '.vscode/**'
+    branches:
+      - main
+    paths-ignore:
+      - 'README.md'
+      - 'LICENSE'
+      - '.github/**'
+      - '.gitignore'
+      - '.git/**'
+      - '.idea/**'
+      - '.vscode/**'
   pull_request:
     branches:
       - main
@@ -41,21 +41,10 @@ jobs:
           force_orphan: true
           commit_message: ${{ github.event.head_commit.message }}
 
-      - name: Get changed folders
-        if: github.event_name == 'push'
-        id: changed-folders
-        uses: tj-actions/changed-files@v46.0.3
-
-      - name: Clear jsdelivr CDN cache
-        if: github.event_name == 'push'
-        env:
-          ALL_CHANGED_FOLDERS: ${{ steps.changed-folders.outputs.all_changed_files }}
+      - name: Clear jsdelivr CDN cache (Only root directory)
         run: |
-          unique_folders=$(echo "${ALL_CHANGED_FOLDERS}" | tr ' ' '\n' | awk -F'/' '{print $1}' | sort -u)
-          for folder in ${unique_folders}; do
-            curl "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/${folder}" \
-            && echo "Cache cleared successfully for ${folder}." || echo "Failed to clear cache for ${folder}."
-          done
+          curl "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/" \
+          && echo "Cache cleared successfully." || echo "Failed to clear cache."
 
       - name: Send Apprise Notification
         run: |
